# -----------------------------------------------------------------
# Production-Quality-Pipeline.yaml
# A hybrid configuration balancing accuracy and performance for English invoices.
# This uses more powerful models than the lean MVP config but should still
# fit within an 8GB RAM environment.
# -----------------------------------------------------------------
pipeline_name: PP-StructureV3

batch_size: 4

# --- CORE SETTINGS ---
use_doc_preprocessor: True
use_table_recognition: True

# --- DISABLED MODULES ---
# We are still keeping the unnecessary pipelines turned off to save memory.
use_seal_recognition: False
use_formula_recognition: False
use_chart_recognition: False
use_region_detection: False

SubModules:
  LayoutDetection:
    module_name: layout_detection
    # --- UPGRADE #1: Back to the Large Layout Model ---
    # The layout detection is the most critical first step. Using the best model
    # here has the biggest downstream impact on quality.
    model_name: PP-DocLayout_plus-L 
    model_dir: null
    batch_size: 4 # Keep batch size low for memory
    threshold: 
      # Using the full, original list of thresholds for the Large model
      0: 0.3
      1: 0.5
      2: 0.4
      3: 0.5
      4: 0.5
      5: 0.5
      6: 0.5
      7: 0.3
      8: 0.5
      9: 0.5
      10: 0.5
      11: 0.5
      12: 0.5
      13: 0.5
      14: 0.5
      15: 0.45
      16: 0.5
      17: 0.5
      18: 0.5
      19: 0.5
    layout_nms: True
    layout_merge_bboxes_mode: "union"

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    batch_size: 4
    use_doc_orientation_classify: True
    use_doc_unwarping: True
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null

  # --- HYBRID OCR SUB-PIPELINE ---
  GeneralOCR:
    pipeline_name: OCR
    batch_size: 4
    text_type: general
    use_doc_preprocessor: False
    use_textline_orientation: True
    SubModules:
      TextDetection:
        module_name: text_detection
        # --- UPGRADE #2: Back to the Server Text Detection Model ---
        # A better detection model provides better inputs to the recognition model.
        model_name: PP-OCRv5_server_det
        model_dir: null
      TextLineOrientation:
        module_name: textline_orientation
        model_name: PP-LCNet_x1_0_textline_ori
        model_dir: null
      TextRecognition:
        module_name: text_recognition
        # We KEEP the specialist English mobile model. It's fast and accurate.
        model_name: en_PP-OCRv4_mobile_rec
        model_dir: null

  # The TableRecognition pipeline remains the same as our last working version.
  TableRecognition:
    pipeline_name: table_recognition_v2
    use_layout_detection: False
    use_doc_preprocessor: False
    use_ocr_model: True
    SubModules:  
      TableClassification:
        module_name: table_classification
        model_name: PP-LCNet_x1_0_table_cls
        model_dir: null
      WiredTableStructureRecognition:
        module_name: table_structure_recognition
        model_name: SLANeXt_wired 
        model_dir: null
      WirelessTableStructureRecognition:
        module_name: table_structure_recognition
        model_name: SLANet_plus
        model_dir: null
      WiredTableCellsDetection:
        module_name: table_cells_detection
        model_name: RT-DETR-L_wired_table_cell_det
        model_dir: null
      WirelessTableCellsDetection:
        module_name: table_cells_detection
        model_name: RT-DETR-L_wireless_table_cell_det
        model_dir: null
      TableOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
    SubPipelines:
      GeneralOCR:
        pipeline_name: OCR
        text_type: general
        use_doc_preprocessor: False
        use_textline_orientation: True
        SubModules:
          TextDetection:
            # Also use the better server model here for consistency
            module_name: text_detection
            model_name: PP-OCRv5_server_det
            model_dir: null
          TextLineOrientation:
            module_name: textline_orientation
            model_name: PP-LCNet_x1_0_textline_ori
            model_dir: null
          TextRecognition:
            module_name: text_recognition
            model_name: en_PP-OCRv4_mobile_rec
            model_dir: null